services:
  - type: web
    name: tv-hamsters-bot
    runtime: node
    repo: https://github.com/outmilker1978/hamsters-theater
    branch: master
    buildCommand: cd bot && npm install
    startCommand: node bot/index.js
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
