name: Release to Telegram

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Telegram
        run: |
          echo "=== Кто админы в канале ==="
          ADMINS=$(curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getChatAdministrators?chat_id=-1003813372615")
          echo "$ADMINS"